config/routes.rb
Rails.application.routes.draw do

  get 'reviews/new'

  get 'reviews/create'

resources :cocktails do
    resources :doses, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create ]
  end
  root to: "cocktails#index"

  resources :doses, only: [ :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, dependent: :destroy, through: :doses
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :title, presence: true
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = Cocktail.find(params[:cocktail_id])
    if @review.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to cocktail_path(@review.cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<%= render "components/banner" %>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-3 col-md-3">

      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url(<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>)">

        <div class="card-category">
          <h3><%= cocktail.name %></h3>
        </div>

        <div class="card-link">
          <%= link_to cocktail_path(cocktail) do %>
            <i class="fa fa-plus-circle fa-stack-2px fa-2x" aria-hidden="true" style="#230004"></i>
          <% end %>
        </div>

      </div>
    </div>
    <% end %>
  </div>
</div>

<%= render "components/footer" %>

app/views/cocktails/new.html.erb
<div class="container">

  <div class="title">
    <h2>New Cocktail</h2>
    <h4>Please, enter your cocktail</h4>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <%= simple_form_for [@cocktail] do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="text-center">
        <%= f.submit "Add a Cocktail", class: "btn btn-primary" %>
        </div>
      <% end %>
      <br>

        <div class="text-center">
          <%= link_to "Back", cocktails_path(@restarant), {:style=>'color:#230004;'} %>
        </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-sm-6">
      <div class="card-name text-center" >
        <h2><strong><%= @cocktail.name %></strong></h2>
        <%= cl_image_tag @cocktail.photo, height: 350, width: 500, crop: :fill %>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6">

        <div class="card-test">
          <h4>Ingredients List: <br><br><% @cocktail.doses.each do |dose| %></h4>
          <p><%= dose.ingredient.name %> : <%= dose.description %>
          <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %></p>
          <% end %>
          <br>
          <p><%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), {:style=>'color:#800000;'} %></p>
        </div>


        <div class="card-test">
          <h4>Reviews: <br><br><% @cocktail.reviews.each do |review| %></h4>
          <p><strong><%= review.title %></strong> : <%= review.content %> <%= review.rating %></p>
          <% end %>
          <br>
          <p><%= link_to "Add a review", new_cocktail_review_path(@cocktail), {:style=>'color:#800000;'} %></p>
        </div>

    </div>
  </div>

    <div class="text-center" style: :color#800000">
      <%= link_to "Back", cocktails_path(@cocktail), {:style=>'color:#800000;'}%>
    </div>
</div>

app/views/doses/new.html.erb
<div class="container">

  <div class="title">
    <h2>New Dose</h2>
    <h4>Please, enter your dose</h4>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :ingredient_id, collection: Ingredient.all %>
        <%= f.input :description %>
        <div class="text-center">
        <%= f.submit "Add a dose", class: "btn btn-primary"%>
        </div>
      <% end %>
      <br>
      <div class="text-center">
        <%= link_to "Back", cocktails_path(@cocktail), {:style=>'color:#230004;'} %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>


  </body>
</html>

app/views/reviews/new.html.erb
<div class="container">

  <div class="title">
    <h2>New Review</h2>
    <h4>Please, enter your review</h4>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <%= simple_form_for [@cocktail, @review] do |f| %>
        <%= f.input :title %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <div class="text-center">
          <%= f.submit "Add a review", class: "btn btn-primary" %>
        </div>
      <% end %>
      <br>
      <div class="text-center">
        <%= link_to "Back", cocktails_path(@cocktail), {:style=>'color:#230004;'} %>
      </div>
    </div>
  </div>
</div>